CompositeMVC/Models/LatestPostsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CompositeMVC.Models
{
    public class LatestPostsModel
    {
        public IEnumerable<Post> Posts { get; set; }
    }
}

CompositeMVC/Models/Post.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CompositeMVC.Models
{
    public class Post
    {
        public string Title { get; set; }
        public string Summary { get; set; }
    }
}

CompositeMVC/Models/TwitterSettings.cs

namespace CompositeMVC.Models
{
    public class TwitterSettings
    {
        public string Handle { get; set; }
    }
}

CompositeMVC/Models/Video.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CompositeMVC.Models
{
    public class Video
    {
        public string Title { get; set; }
        public string Url { get; set; }
    }
}

CompositeMVC/Models/WidgetDefinition.cs

namespace CompositeMVC.Models
{
    public class SimpleWidgetDefinition
    {
        public SimpleWidgetDefinition(string name, string controller, string action, object routeValues = null)
        {
            Name = name;
            Controller = controller;
            Action = action;
            RouteValues = routeValues;            
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public object RouteValues { get; set; }
    }
}

CompositeMVC/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using CompositeMVC.Models;

namespace CompositeMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var widgets = new List<SimpleWidgetDefinition>
            {
                new SimpleWidgetDefinition("Latest Posts", "home", "latestposts"),
                new SimpleWidgetDefinition("Featured Video", "home", "featuredvideo"),
                new SimpleWidgetDefinition("Latest Tweets", "home", "tweets")
            };

            ViewBag.Message = "Welcome to ASP.NET MVC!";

            return View(widgets);
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult LatestPosts()
        {
            var posts = new List<Post>
            {
                new Post { Title = "Post 1", Summary = "Post 1 Summary" },
                new Post { Title = "Post 2", Summary = "Post 2 Summary" },
                new Post { Title = "Post 3", Summary = "Post 3 Summary" }
            };

            return PartialView(posts);
        }

        public ActionResult FeaturedVideo()
        {
            var featured = new Video
            {
                Title = "Brad Wilson - Microsoft's Modern Web Stack",
                Url = "http://vimeo.com/43603472"
            };

            return PartialView(featured);
        }

        public ActionResult Tweets()
        {
            var settings = new TwitterSettings { Handle = "benfosterdev" };
            return PartialView(settings);
        }
    }
}

CompositeMVC/Controllers/WidgetController.cs
using System.Web.Mvc;
using CompositeMVC.Application;

namespace CompositeMVC.Controllers
{
    public class WidgetController : Controller
    {
        //
        // GET: /Widget/

        public ActionResult Index(string id)
        {
            var pageBuilder = new PageBuilder(new WidgetCatalog());
            var model = pageBuilder.BuildPage(id);
            return View(model);
        }

    }
}

CompositeMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Us";
}

<h2>About</h2>
<p>
     Put content here.
</p>

CompositeMVC/Views/Home/FeaturedVideo.cshtml
@model CompositeMVC.Models.Video

<a href="@Model.Url" class="embed">View Video</a>

<h3>@Model.Title</h3>

<script type="text/javascript">

    $(function () {

        $('a.embed').each(function () {
            var $link = $(this);
            var width = $link.parent().width();
            var videoUrl = 'http://vimeo.com/api/oembed.json?width=' + width + '&url=' + $(this).attr('href');

            $.getJSON(videoUrl, function (data) {
                var container = $('<div></div>').html(data.html);
                $link.after(container).hide();
            });
        });

    });

</script>

CompositeMVC/Views/Home/Index.cshtml
@model IEnumerable<CompositeMVC.Models.SimpleWidgetDefinition>
@{
    ViewBag.Title = "Home Page";
}

<h2>@ViewBag.Message</h2>
<p>
    To learn more about ASP.NET MVC visit <a href="http://asp.net/mvc" title="ASP.NET MVC Website">http://asp.net/mvc</a>.
</p>

@foreach (var widget in Model) { 
    <div class="widget">
        <h2>@widget.Name</h2>
        @Html.Action(widget.Action, widget.Controller, widget.RouteValues)
    </div>
}

<div class="clear"></div>

CompositeMVC/Views/Home/LatestPosts.cshtml
@model IEnumerable<CompositeMVC.Models.Post>

<ul>
@foreach (var post in Model) { 
    <li>
        <h3><a href="#">@post.Title</a></h3>
        <p>
            @post.Summary
        </p>
    </li>
}
</ul>

CompositeMVC/Views/Home/Tweets.cshtml
@model CompositeMVC.Models.TwitterSettings

<script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
<script>
    new TWTR.Widget({
        version: 2,
        type: 'profile',
        rpp: 3,
        interval: 30000,
        width: 'auto',
        height: 300,
        theme: {
            shell: {
                background: '#ececec',
                color: '#000'
            },
            tweets: {
                background: '#ececec',
                color: '#474747',
                links: '#00ccdb'
            }
        },
        features: {
            scrollbar: false,
            loop: false,
            live: true,
            behavior: 'all'
        }
    }).render().setUser('@Model.Handle').start();
</script>

CompositeMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>My MVC Application</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Widgets", "Index", "Widget")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
        @* Make sure you've added this one line to your LAYOUT or MASTER PAGE *@
        @StackExchange.Profiling.MiniProfiler.RenderIncludes()
</body>
</html>

CompositeMVC/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}

CompositeMVC/Views/Widget/Index.cshtml
@using CompositeMVC.Application
@model PageModel

@foreach (var widget in Model.Widgets) {
        
    <div class="widget">
        <h2>@widget.Title</h2>
        @widget.Render(Html)
    </div>
}

<div class="clear"></div>

CompositeMVC/Views/Widget/Posts.cshtml
@model CompositeMVC.Application.Widgets.PostsWidget

<ul>
@foreach (var post in Model.Posts) { 
    <li>
        <h3><a href="#">@post.Title</a></h3>
        <p>
            @post.Summary
        </p>
    </li>
}
</ul>

CompositeMVC/Views/Widget/Tweets.cshtml
@model CompositeMVC.Application.Widgets.TwitterWidget
<script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
<script>
    new TWTR.Widget({
        version: 2,
        type: 'profile',
        rpp: 3,
        interval: 30000,
        width: 'auto',
        height: 300,
        theme: {
            shell: {
                background: '#ececec',
                color: '#000'
            },
            tweets: {
                background: '#ececec',
                color: '#474747',
                links: '#00ccdb'
            }
        },
        features: {
            scrollbar: false,
            loop: false,
            live: true,
            behavior: 'all'
        }
    }).render().setUser('@Model.Settings["handle"]').start();
</script>

CompositeMVC/Views/Widget/Video.cshtml
@model CompositeMVC.Application.Widgets.VideoWidget

<a href="@Model.Settings["url"]" class="embed">View Video</a>
<div id="video"></div>
<h3>@Model.Settings["title"]</h3>


<script type="text/javascript">

    $(function () {

        $('a.embed').each(function () {
            var $link = $(this);
            var width = $link.parent().width();
            var videoUrl = 'http://vimeo.com/api/oembed.json?url=' + $(this).attr('href') + '&width=' + width + "&callback=embedVideo";

            var script = document.createElement("script");
            script.type = 'text/javascript';
            script.src = videoUrl;
            $('head').append(script);
        });

    });

    function embedVideo(data) {
        $('.embed').hide();
        $("#video").html(data.html);
    }

</script>